### ISSUE TITLE
Meteor 1.3 install package error

### ISSUE THREAD

**Issue by grinono** [gwendall/meteor-blaze-to-react#7]
Installing all the react modules did not fix the issue. Any idea?

I20160419-22:11:42.213(2)? [Error: Can't find npm module 'react-addons-linked-state-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160419-22:11:42.216(2)? [Error: Can't find npm module 'react-addons-create-fragment/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160419-22:11:42.219(2)? [Error: Can't find npm module 'react-addons-update/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160419-22:11:42.223(2)? [Error: Can't find npm module 'react-addons-test-utils/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160419-22:11:42.226(2)? [Error: Can't find npm module 'react-addons-perf/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
W20160419-22:11:42.227(2)? (STDERR) WARNING: npm peer requirements not installed:
W20160419-22:11:42.227(2)? (STDERR)  - react@15.0.1 installed, react@0.14.x needed
W20160419-22:11:42.227(2)? (STDERR)  - react-dom@15.0.1 installed, react-dom@0.14.x needed
W20160419-22:11:42.227(2)? (STDERR)  - react-addons-transition-group@15.0.1 installed, react-addons-transition-group@0.14.x needed
W20160419-22:11:42.227(2)? (STDERR)  - react-addons-css-transition-group@15.0.1 installed, react-addons-css-transition-group@0.14.x needed
W20160419-22:11:42.227(2)? (STDERR)  - react-addons-linked-state-mixin@0.14.x not installed.
W20160419-22:11:42.227(2)? (STDERR)  - react-addons-create-fragment@0.14.x not installed.
W20160419-22:11:42.227(2)? (STDERR)  - react-addons-update@0.14.x not installed.
W20160419-22:11:42.227(2)? (STDERR)  - react-addons-pure-render-mixin@15.0.1 installed, react-addons-pure-render-mixin@0.14.x needed
W20160419-22:11:42.228(2)? (STDERR)  - react-addons-test-utils@0.14.x not installed.
W20160419-22:11:42.228(2)? (STDERR)  - react-addons-perf@0.14.x not installed.
W20160419-22:11:42.228(2)? (STDERR)
W20160419-22:11:42.228(2)? (STDERR) Read more about installing npm peer dependencies:
W20160419-22:11:42.228(2)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160419-22:11:42.228(2)? (STDERR)
W20160419-22:11:42.354(2)? (STDERR)
W20160419-22:11:42.354(2)? (STDERR) /Users/bartelverkruijssen/.meteor/packages/meteor-tool/.1.3.2_2.11n51pe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160419-22:11:42.355(2)? (STDERR)                             throw(ex);
W20160419-22:11:42.355(2)? (STDERR)                                   ^
W20160419-22:11:42.370(2)? (STDERR) Error: Can't find npm module 'react-addons-linked-state-mixin'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160419-22:11:42.370(2)? (STDERR)     at Object.Npm.require (/Users/bartelverkruijssen/Google Drive/Talqs/Talqs General/development/Talqs - General/reactApp/.meteor/local/build/programs/server/boot.js:195:17)
W20160419-22:11:42.370(2)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
W20160419-22:11:42.370(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
W20160419-22:11:42.370(2)? (STDERR)     at meteorInstall.node_modules.meteor.react-runtime.react-runtime.js (packages/react-runtime/react-runtime.js:31:21)
W20160419-22:11:42.370(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160419-22:11:42.370(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160419-22:11:42.370(2)? (STDERR)     at /Users/bartelverkruijssen/Google Drive/Talqs/Talqs General/development/Talqs - General/reactApp/.meteor/local/build/programs/server/packages/react-runtime.js:86:15
W20160419-22:11:42.370(2)? (STDERR)     at /Users/bartelverkruijssen/Google Drive/Talqs/Talqs General/development/Talqs - General/reactApp/.meteor/local/build/programs/server/packages/react-runtime.js:99:3
W20160419-22:11:42.370(2)? (STDERR)     at /Users/bartelverkruijssen/Google Drive/Talqs/Talqs General/development/Talqs - General/reactApp/.meteor/local/build/programs/server/boot.js:283:10
W20160419-22:11:42.370(2)? (STDERR)     at Array.forEach (native)

**Comment by grinono** [comment]
i have the same issue, at meteor update

**Comment by noglows** [comment]
I'm having the same issue. @gwendall - any ideas for a fix?

**Comment by diegonc** [comment]
@noglows @gwendall 
I think the problem is that the last version of the package (1.0.0 according to package.js) is not yet published to atmosphere so the package is pulling react package; which conflicts with the ones installed with NPM.

**Comment by acomito** [comment]
Same problem here.

**Comment by tankhuu** [comment]
is this package still supported? I'm having the same problem here.

**Comment by acomito** [comment]
@jackiekhuu-work I can't remember how I get around this. It was ages ago. think there was an issue with where you need to change the static-html package for a blaze templates package, or vice versa.

**Comment by grinono** [comment]
you should stop using this package. Better direct React. Most libs that are active developed have react alternative.

**Comment by tankhuu** [comment]
You are right, I used another package and It's working well.
https://github.com/gadicc/meteor-blaze-react-component
